fg = figure;

subplot(4, 1, 1);
plot_traces_helper(fine_time, Qe_rand, ...
    'firing rate for a random excitatory node', ...
    'frequency (1/s)', [0 30]);

subplot(4, 1, 2);
plot_traces_helper(fine_time, Ve_rand, ...
    'voltage for a random excitatory node', ...
    'voltage (mV)', [-70 -40]);

subplot(4, 1, 3);
plot_traces_helper(fine_time, Qe_avg, ...
    'average firing rate for all nodes in zone', ...
    'frequency (1/s)', [0 30]);

subplot(4, 1, 4);
plot_traces_helper(fine_time, Ve_avg, ...
    'average voltage for all nodes in zone', ...
    'voltage (mV)', [-70 -40]);

% save figure
saveas(fg, TRACES_FIG);
